#!/usr/bin/env python3
import libtmux
import time
tmuxServer = libtmux.Server()
session = tmuxServer.new_session("contrSSH")
window = session.attached_window
window.split_window(vertical=False)
window.panes[1].split_window(vertical=True)

window.panes[0].send_keys("bhunter")
time.sleep(1)
window.panes[1].send_keys("tail -f /var/log/bhunter/honeypot.log")
window.panes[2].send_keys("tail -f /var/log/bhunter/attack.log")

#libtmux.Server().kill_session("contrSSH"
